CREATE TABLE IF NOT EXISTS websites (
    id integer PRIMARY KEY ,
    url TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)